name = 'leanlog'
pages_build_output_dir = "./dist"
compatibility_date = "2026-05-17"
compatibility_flags = ["nodejs_compat"]

[vars]
VITE_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsubGVhbmxvZy52ZGhzbi5jb20k"
VITE_POSTHOG_API_KEY = "phc_LtP1UAE1BEhuRqcbt8t5dyCFWBQ9ncJ4DvqwCWTbchs"
VITE_POSTHOG_HOST = "https://us.i.posthog.com"

[[d1_databases]]
binding = "DB"
database_name = "leanlog-db"
database_id = "3747f59b-37ac-452f-93cd-8965e704a063"
preview_database_id = "DB"
migrations_dir = "../../packages/data-d1/drizzle"

[env.preview]
[env.preview.vars]
VITE_CLERK_PUBLISHABLE_KEY = "pk_test_bmV3LXdpbGRjYXQtMzkuY2xlcmsuYWNjb3VudHMuZGV2JA"
VITE_POSTHOG_API_KEY = "phc_LtP1UAE1BEhuRqcbt8t5dyCFWBQ9ncJ4DvqwCWTbchs"
VITE_POSTHOG_HOST = "https://us.i.posthog.com"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "leanlog-db-dev"
database_id = "2bb90936-0975-43b5-bf32-fa28f4b1fb59"
preview_database_id = "DB"
migrations_dir = "../../packages/data-d1/drizzle"
