name = 'leanlog'
pages_build_output_dir = "./dist"
compatibility_date = "2026-05-17"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "leanlog-db"
database_id = "3747f59b-37ac-452f-93cd-8965e704a063"
