DROP TABLE IF EXISTS nutrition_database_ingredients;
DROP TABLE IF EXISTS meal_template_ingredients;
DROP TABLE IF EXISTS meal_templates;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS meals;
DROP TABLE IF EXISTS daily_meal_logs;
DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS d1_migrations;
