// Types for drizzle-kit's generated migrations.js (not regenerated by drizzle-kit).
declare const bundle: {
  journal: { entries: { idx: number; when: number; tag: string; breakpoints: boolean }[] };
  migrations: Record<string, string>;
};
export default bundle;
